package spanning.atm;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Raul' at '2/20/16 5:19 PM' with Gradle 2.11
 *
 * @author Raul, @date 2/20/16 5:19 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
