import org.junit.Test;

import spanning.atm.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Raul' at '2/20/16 5:19 PM' with Gradle 2.11
 *
 * @author Raul, @date 2/20/16 5:19 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
